import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";

import { createDocument } from "../features/documents/document.api";
import { getFolders } from "../features/folders/folder.api";
import type { Folder } from "../features/folders/folder.types";
import { getProjects } from "../features/projects/project.api";
import type { Project } from "../features/projects/project.types";
import { DOCUMENT_TEMPLATES } from "../features/document-templates/document-template.data";
import type { DocumentTemplate } from "../features/document-templates/document-template.types";

import { Card, CardBody, CardHeader } from "../components/ui/Card";
import { Button } from "../components/ui/Button";
import { Breadcrumb } from "../components/ui/Breadcrumb";

function formatFileSize(bytes: number): string {
  if (bytes === 0) return "0 B";
  const k = 1024;
  const sizes = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`;
}

function generateTemplateFile(template: DocumentTemplate, title: string): File {
  const sanitizeName = (title || template.name)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  const fileName = `${sanitizeName || template.id}.md`;
  return new File([template.scaffoldContent], fileName, {
    type: "text/markdown",
  });
}

export default function DocumentCreatePage() {
  const navigate = useNavigate();

  const [selectedTemplateId, setSelectedTemplateId] = useState<string>("blank");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [folderId, setFolderId] = useState("");
  const [projectId, setProjectId] = useState("");
  const [tagsInput, setTagsInput] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [isAutoGeneratedFile, setIsAutoGeneratedFile] = useState(false);

  const [folders, setFolders] = useState<Folder[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    async function loadFoldersAndProjects() {
      try {
        const [foldersRes, projectsRes] = await Promise.all([
          getFolders(),
          getProjects(),
        ]);
        setFolders(foldersRes.data.folders);
        setProjects(projectsRes.data.projects);
      } catch {
        // Silent catch
      }
    }

    void loadFoldersAndProjects();
  }, []);

  const activeTemplate = DOCUMENT_TEMPLATES.find(
    (t) => t.id === selectedTemplateId
  );

  function handleSelectTemplate(templateId: string) {
    setSelectedTemplateId(templateId);
    setError("");

    if (templateId === "blank") {
      if (isAutoGeneratedFile) {
        setFile(null);
        setIsAutoGeneratedFile(false);
      }
      return;
    }

    const template = DOCUMENT_TEMPLATES.find((t) => t.id === templateId);
    if (!template) return;

    setTitle(template.titlePrefix);
    setDescription(template.scaffoldContent.slice(0, 950));
    setTagsInput(template.defaultTags.join(", "));

    if (!file || isAutoGeneratedFile) {
      const generatedFile = generateTemplateFile(template, template.titlePrefix);
      setFile(generatedFile);
      setIsAutoGeneratedFile(true);
    }
  }

  function handleFileChange(selectedFile: File | null) {
    setFile(selectedFile);
    setIsAutoGeneratedFile(false);
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    const trimmedTitle = title.trim();
    if (trimmedTitle.length < 2 || trimmedTitle.length > 200) {
      setError("Title must be between 2 and 200 characters");
      return;
    }

    if (description.length > 1000) {
      setError("Description must not exceed 1000 characters");
      return;
    }

    if (!file) {
      setError("Document file is required");
      return;
    }

    const parsedTags = tagsInput
      .split(",")
      .map((t) => t.trim().toLowerCase())
      .filter(Boolean);

    setCreating(true);
    setError("");

    try {
      const response = await createDocument({
        title: trimmedTitle,
        description: description.trim() || undefined,
        folderId: folderId || null,
        projectId: projectId || null,
        tags: parsedTags.length > 0 ? parsedTags : undefined,
        templateId: selectedTemplateId !== "blank" ? selectedTemplateId : undefined,
        file,
      });

      navigate(`/documents/${response.data.id}`);
    } catch {
      setError("Failed to create document");
    } finally {
      setCreating(false);
    }
  }

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <Breadcrumb
        items={[
          { label: "Documents", href: "/documents" },
          { label: "Create Document" },
        ]}
      />

      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-extrabold text-gray-900 dark:text-white">
            Create New Document
          </h1>
          <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">
            Author a blank document or start with a pre-filled technical template.
          </p>
        </div>
        <Link to="/documents">
          <Button variant="outline" size="sm">
            Cancel
          </Button>
        </Link>
      </div>

      {error && (
        <div className="p-3 bg-red-50 dark:bg-red-900/30 text-red-700 dark:text-red-400 rounded-md text-sm font-medium">
          {error}
        </div>
      )}

      {/* Starting Point Templates */}
      <Card>
        <CardHeader>
          <h3 className="font-bold text-gray-900 dark:text-white text-base">
            Document Starting Point
          </h3>
        </CardHeader>
        <CardBody className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
            <button
              type="button"
              onClick={() => handleSelectTemplate("blank")}
              className={`p-4 text-left rounded-lg border text-sm transition-all ${
                selectedTemplateId === "blank"
                  ? "border-indigo-600 ring-2 ring-indigo-500 bg-indigo-50/50 dark:bg-indigo-900/30 font-semibold"
                  : "border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:border-gray-300"
              }`}
            >
              <div className="text-base mb-1">📄 Blank Document</div>
              <div className="text-xs text-gray-500 dark:text-gray-400 font-normal">
                Standard document without pre-filled scaffolding
              </div>
            </button>

            {DOCUMENT_TEMPLATES.map((tmpl) => {
              const isSelected = selectedTemplateId === tmpl.id;
              return (
                <button
                  key={tmpl.id}
                  type="button"
                  onClick={() => handleSelectTemplate(tmpl.id)}
                  className={`p-4 text-left rounded-lg border text-sm transition-all ${
                    isSelected
                      ? "border-indigo-600 ring-2 ring-indigo-500 bg-indigo-50/50 dark:bg-indigo-900/30 font-semibold"
                      : "border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:border-gray-300"
                  }`}
                >
                  <div className="text-base mb-1">
                    {tmpl.id === "adr" ? "🏗️ " : tmpl.id === "tech-spec" ? "📐 " : "🔧 "}
                    {tmpl.name}
                  </div>
                  <div className="text-xs text-gray-500 dark:text-gray-400 font-normal line-clamp-2">
                    {tmpl.description}
                  </div>
                </button>
              );
            })}
          </div>

          {activeTemplate && (
            <div className="p-4 bg-indigo-50/70 dark:bg-indigo-900/20 border border-indigo-200 dark:border-indigo-800 rounded-lg text-xs space-y-1">
              <span className="font-bold text-indigo-900 dark:text-indigo-300">
                Template Preview: {activeTemplate.name}
              </span>
              <p className="text-gray-700 dark:text-gray-300">
                {activeTemplate.description}
              </p>
              <p className="text-gray-500 dark:text-gray-400">
                Included Sections: {activeTemplate.sections.join(" • ")}
              </p>
            </div>
          )}
        </CardBody>
      </Card>

      {/* Authoring Form */}
      <Card>
        <CardBody>
          <form onSubmit={(e) => void handleSubmit(e)} className="space-y-4">
            <div>
              <label
                htmlFor="title"
                className="block text-sm font-medium text-gray-700 dark:text-gray-300"
              >
                Document Title *
              </label>
              <input
                id="title"
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                required
                minLength={2}
                maxLength={200}
                placeholder="Enter a descriptive title"
                className="mt-1 block w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-md shadow-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm"
              />
            </div>

            <div>
              <label
                htmlFor="description"
                className="block text-sm font-medium text-gray-700 dark:text-gray-300"
              >
                Description / Summary Notes
              </label>
              <textarea
                id="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                maxLength={1000}
                rows={4}
                placeholder="Enter document summary or description"
                className="mt-1 block w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-md shadow-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label
                  htmlFor="folder"
                  className="block text-sm font-medium text-gray-700 dark:text-gray-300"
                >
                  Folder
                </label>
                <select
                  id="folder"
                  value={folderId}
                  onChange={(e) => setFolderId(e.target.value)}
                  className="mt-1 block w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-md shadow-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm"
                >
                  <option value="">-- No Folder (Unfiled) --</option>
                  {folders.map((f) => (
                    <option key={f.id} value={f.id}>
                      {f.name}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label
                  htmlFor="project"
                  className="block text-sm font-medium text-gray-700 dark:text-gray-300"
                >
                  Project Context
                </label>
                <select
                  id="project"
                  value={projectId}
                  onChange={(e) => setProjectId(e.target.value)}
                  className="mt-1 block w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-md shadow-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm"
                >
                  <option value="">-- No Project --</option>
                  {projects.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.name}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div>
              <label
                htmlFor="tags"
                className="block text-sm font-medium text-gray-700 dark:text-gray-300"
              >
                Tags (comma-separated)
              </label>
              <input
                id="tags"
                type="text"
                value={tagsInput}
                onChange={(e) => setTagsInput(e.target.value)}
                placeholder="e.g. engineering, spec, v2"
                className="mt-1 block w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-md shadow-sm bg-white dark:bg-gray-800 text-gray-900 dark:text-white text-sm"
              />
            </div>

            <div>
              <label
                htmlFor="file"
                className="block text-sm font-medium text-gray-700 dark:text-gray-300"
              >
                Document File *
              </label>
              <input
                id="file"
                type="file"
                onChange={(e) => handleFileChange(e.target.files?.[0] || null)}
                className="mt-1 block w-full text-sm text-gray-500 dark:text-gray-400 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100"
              />
              {file && (
                <div className="mt-2 p-3 bg-gray-50 dark:bg-gray-800/80 rounded-md border border-gray-200 dark:border-gray-700 text-xs">
                  <span className="font-semibold text-gray-900 dark:text-white">
                    {isAutoGeneratedFile ? "📄 Template Scaffolding File: " : "Selected: "}
                    {file.name} ({formatFileSize(file.size)})
                  </span>
                </div>
              )}
            </div>

            <div className="pt-4 flex gap-3">
              <Button type="submit" variant="primary" isLoading={creating}>
                Create Document
              </Button>
              <Link to="/documents">
                <Button type="button" variant="secondary">
                  Cancel
                </Button>
              </Link>
            </div>
          </form>
        </CardBody>
      </Card>
    </div>
  );
}
