import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';

import { createDocument } from '../features/documents/document.api';
import { getFolders } from '../features/folders/folder.api';
import type { Folder } from '../features/folders/folder.types';
import { getProjects } from '../features/projects/project.api';
import type { Project } from '../features/projects/project.types';
import { DOCUMENT_TEMPLATES } from '../features/document-templates/document-template.data';
import type { DocumentTemplate } from '../features/document-templates/document-template.types';

function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`;
}

function generateTemplateFile(template: DocumentTemplate, title: string): File {
  const sanitizeName = (title || template.name)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
  const fileName = `${sanitizeName || template.id}.md`;
  return new File([template.scaffoldContent], fileName, {
    type: 'text/markdown',
  });
}

export default function DocumentCreatePage() {
  const navigate = useNavigate();

  const [selectedTemplateId, setSelectedTemplateId] = useState<string>('blank');
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [folderId, setFolderId] = useState('');
  const [projectId, setProjectId] = useState('');
  const [tagsInput, setTagsInput] = useState('');
  const [file, setFile] = useState<File | null>(null);
  const [isAutoGeneratedFile, setIsAutoGeneratedFile] = useState(false);

  const [folders, setFolders] = useState<Folder[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    async function loadFoldersAndProjects() {
      try {
        const [foldersRes, projectsRes] = await Promise.all([
          getFolders(),
          getProjects(),
        ]);
        setFolders(foldersRes.data.folders);
        setProjects(projectsRes.data.projects);
      } catch {
        // Silent catch
      }
    }

    void loadFoldersAndProjects();
  }, []);

  const activeTemplate = DOCUMENT_TEMPLATES.find(
    (t) => t.id === selectedTemplateId,
  );

  function handleSelectTemplate(templateId: string) {
    setSelectedTemplateId(templateId);
    setError('');

    if (templateId === 'blank') {
      if (isAutoGeneratedFile) {
        setFile(null);
        setIsAutoGeneratedFile(false);
      }
      return;
    }

    const template = DOCUMENT_TEMPLATES.find((t) => t.id === templateId);
    if (!template) return;

    setTitle(template.titlePrefix);
    setDescription(template.scaffoldContent.slice(0, 950));
    setTagsInput(template.defaultTags.join(', '));

    if (!file || isAutoGeneratedFile) {
      const generatedFile = generateTemplateFile(template, template.titlePrefix);
      setFile(generatedFile);
      setIsAutoGeneratedFile(true);
    }
  }

  function handleFileChange(selectedFile: File | null) {
    setFile(selectedFile);
    setIsAutoGeneratedFile(false);
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    const trimmedTitle = title.trim();
    if (trimmedTitle.length < 2 || trimmedTitle.length > 200) {
      setError('Title must be between 2 and 200 characters');
      return;
    }

    if (description.length > 1000) {
      setError('Description must not exceed 1000 characters');
      return;
    }

    if (!file) {
      setError('Document file is required');
      return;
    }

    const parsedTags = tagsInput
      .split(',')
      .map((t) => t.trim().toLowerCase())
      .filter(Boolean);

    setCreating(true);
    setError('');

    try {
      const response = await createDocument({
        title: trimmedTitle,
        description: description.trim() || undefined,
        folderId: folderId || null,
        projectId: projectId || null,
        tags: parsedTags.length > 0 ? parsedTags : undefined,
        templateId: selectedTemplateId !== 'blank' ? selectedTemplateId : undefined,
        file,
      });

      navigate(`/documents/${response.data.id}`);
    } catch {
      setError('Failed to create document');
    } finally {
      setCreating(false);
    }
  }

  return (
    <main
      style={{
        textAlign: 'left',
        maxWidth: '850px',
        margin: '0 auto',
        padding: '1rem',
      }}
    >
      <header
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: '1.5rem',
        }}
      >
        <div>
          <h1 style={{ margin: 0 }}>Create Document</h1>
          <p style={{ margin: '0.25rem 0 0 0', color: '#666', fontSize: '0.95rem' }}>
            Create a blank document or start with a structured technical template.
          </p>
        </div>
        <Link to="/documents">Cancel</Link>
      </header>

      {error && (
        <div
          style={{
            padding: '0.75rem 1rem',
            background: '#fff2f2',
            border: '1px solid #ffcdd2',
            borderRadius: '4px',
            color: '#c62828',
            marginBottom: '1.25rem',
          }}
        >
          {error}
        </div>
      )}

      {/* Template Selection Section */}
      <section style={{ marginBottom: '2rem' }}>
        <label
          style={{
            display: 'block',
            fontWeight: 'bold',
            marginBottom: '0.75rem',
            fontSize: '1rem',
          }}
        >
          Document Starting Point
        </label>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
            gap: '0.75rem',
          }}
        >
          <button
            type="button"
            onClick={() => handleSelectTemplate('blank')}
            style={{
              padding: '0.85rem',
              textAlign: 'left',
              border:
                selectedTemplateId === 'blank'
                  ? '2px solid #1976d2'
                  : '1px solid #ccc',
              borderRadius: '6px',
              background: selectedTemplateId === 'blank' ? '#e3f2fd' : '#fff',
              cursor: 'pointer',
              fontWeight: selectedTemplateId === 'blank' ? 'bold' : 'normal',
            }}
          >
            <div style={{ fontSize: '1.1rem', marginBottom: '0.25rem' }}>📄 Blank Document</div>
            <div style={{ fontSize: '0.8rem', color: '#666' }}>Standard document without pre-filled scaffolding</div>
          </button>

          {DOCUMENT_TEMPLATES.map((tmpl) => {
            const isSelected = selectedTemplateId === tmpl.id;
            return (
              <button
                key={tmpl.id}
                type="button"
                onClick={() => handleSelectTemplate(tmpl.id)}
                style={{
                  padding: '0.85rem',
                  textAlign: 'left',
                  border: isSelected ? '2px solid #1976d2' : '1px solid #ccc',
                  borderRadius: '6px',
                  background: isSelected ? '#e3f2fd' : '#fff',
                  cursor: 'pointer',
                  fontWeight: isSelected ? 'bold' : 'normal',
                }}
              >
                <div style={{ fontSize: '1.1rem', marginBottom: '0.25rem' }}>
                  {tmpl.id === 'adr' ? '🏗️ ' : tmpl.id === 'tech-spec' ? '📐 ' : '🔧 '}
                  {tmpl.name}
                </div>
                <div style={{ fontSize: '0.8rem', color: '#666' }}>
                  {tmpl.description.slice(0, 60)}...
                </div>
              </button>
            );
          })}
        </div>
      </section>

      {/* Template Preview Card */}
      {activeTemplate && (
        <div
          style={{
            marginBottom: '1.5rem',
            padding: '1rem',
            background: '#f5f9ff',
            border: '1px solid #bbdefb',
            borderRadius: '6px',
          }}
        >
          <h3 style={{ margin: '0 0 0.5rem 0', color: '#1565c0' }}>
            Template Preview: {activeTemplate.name}
          </h3>
          <p style={{ margin: '0 0 0.75rem 0', fontSize: '0.9rem', color: '#333' }}>
            {activeTemplate.description}
          </p>
          <div style={{ fontSize: '0.85rem', color: '#555' }}>
            <strong>Included Sections:</strong> {activeTemplate.sections.join(' • ')}
          </div>
        </div>
      )}

      <form onSubmit={(e) => void handleSubmit(e)}>
        <div style={{ marginBottom: '1.25rem' }}>
          <label
            htmlFor="title"
            style={{ display: 'block', fontWeight: 'bold', marginBottom: '0.5rem' }}
          >
            Title *
          </label>
          <input
            id="title"
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            required
            minLength={2}
            maxLength={200}
            placeholder="Enter a descriptive title"
            style={{ width: '100%', padding: '0.5rem', boxSizing: 'border-box' }}
          />
        </div>

        <div style={{ marginBottom: '1.25rem' }}>
          <label
            htmlFor="description"
            style={{ display: 'block', fontWeight: 'bold', marginBottom: '0.5rem' }}
          >
            Description / Summary Notes
          </label>
          <textarea
            id="description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            maxLength={1000}
            rows={5}
            placeholder="Enter document description or summary notes (optional)"
            style={{ width: '100%', padding: '0.5rem', boxSizing: 'border-box' }}
          />
        </div>

        <div style={{ marginBottom: '1.25rem' }}>
          <label
            htmlFor="folder"
            style={{ display: 'block', fontWeight: 'bold', marginBottom: '0.5rem' }}
          >
            Folder
          </label>
          <select
            id="folder"
            value={folderId}
            onChange={(e) => setFolderId(e.target.value)}
            style={{ width: '100%', padding: '0.5rem', boxSizing: 'border-box' }}
          >
            <option value="">-- No Folder (Unfiled) --</option>
            {folders.map((f) => (
              <option key={f.id} value={f.id}>
                {f.name}
              </option>
            ))}
          </select>
        </div>

        <div style={{ marginBottom: '1.25rem' }}>
          <label
            htmlFor="project"
            style={{ display: 'block', fontWeight: 'bold', marginBottom: '0.5rem' }}
          >
            Project Context (optional)
          </label>
          <select
            id="project"
            value={projectId}
            onChange={(e) => setProjectId(e.target.value)}
            style={{ width: '100%', padding: '0.5rem', boxSizing: 'border-box' }}
          >
            <option value="">-- No Project --</option>
            {projects.map((p) => (
              <option key={p.id} value={p.id}>
                {p.name}
              </option>
            ))}
          </select>
        </div>

        <div style={{ marginBottom: '1.25rem' }}>
          <label
            htmlFor="tags"
            style={{ display: 'block', fontWeight: 'bold', marginBottom: '0.5rem' }}
          >
            Tags (comma-separated)
          </label>
          <input
            id="tags"
            type="text"
            value={tagsInput}
            onChange={(e) => setTagsInput(e.target.value)}
            placeholder="e.g. engineering, spec, v2"
            style={{ width: '100%', padding: '0.5rem', boxSizing: 'border-box' }}
          />
        </div>

        <div style={{ marginBottom: '1.25rem' }}>
          <label
            htmlFor="file"
            style={{ display: 'block', fontWeight: 'bold', marginBottom: '0.5rem' }}
          >
            Document File *
          </label>
          <input
            id="file"
            type="file"
            onChange={(e) => handleFileChange(e.target.files?.[0] || null)}
          />
          {file && (
            <div
              style={{
                marginTop: '0.75rem',
                padding: '0.75rem',
                background: isAutoGeneratedFile ? '#f1f8e9' : '#fafafa',
                border: isAutoGeneratedFile ? '1px solid #c8e6c9' : '1px solid #eee',
                borderRadius: '4px',
              }}
            >
              <p style={{ margin: 0, fontSize: '0.9rem', color: '#333' }}>
                {isAutoGeneratedFile ? '📄 Template Scaffolding File: ' : 'Selected: '}
                <strong>{file.name}</strong> ({formatFileSize(file.size)})
              </p>
              {isAutoGeneratedFile && (
                <p style={{ margin: '0.25rem 0 0 0', fontSize: '0.8rem', color: '#2e7d32' }}>
                  Auto-generated Markdown file from selected template. You can upload your own custom file to replace it.
                </p>
              )}
            </div>
          )}
        </div>

        <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center', marginTop: '1.5rem' }}>
          <button type="submit" disabled={creating}>
            {creating ? 'Creating...' : 'Create Document'}
          </button>
          <Link to="/documents">Cancel</Link>
        </div>
      </form>
    </main>
  );
}
